version: "2"

services:
  mysql:
    restart: always
    image: mysql:5.7.18
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=actio
      - MYSQL_USER=actio 
      - MYSQL_PASSWORD=actio
      
  engine:
    image: actio/engine
    restart: always
    expose:
      - 8081
    environment:
      - SPRING_DATASOURCE_TEST-ON-BORROW = true
      - SPRING_DATASOURCE_VALIDATION-QUERY = "SELECT 1"
      - SPRING_DATASOURCE_TESTONBORROW = 1
      - SPRING_DATASOURCE_VALIDATIONQUERY = "SELECT 1"
      - SPRING_DATASOURCE_VALIDATIONINTERVAL = 30000
      - SPRING_DATASOURCE_MAXACTIVE = 50
      - SPRING_DATASOURCE_MAXIDLE = 50
      - SPRING_DATASOURCE_MINIDLE = 5
      - SPRING_DATASOURCE_INITIALSIZE = 2
      - SPRING_DATASOURCE_MAXWAIT = 30000
      - SPRING_DATASOURCE_TESTONRETURN = false
      - SPRING_DATASOURCE_TESTWHILEIDLE = false
      - SPRING_DATASOURCE_TIMEBETWEENEVICTIONRUNSMILLIS = 5000
      - SPRING_DATASOURCE_MINEVICTABLEIDLETIMEMILLIS = 60000
      - SPRING_DATASOURCE_REMOVEABANDONED = false
      - SPRING_DATASOURCE_REMOVEABANDONEDTIMEOUT = 60
      - SPRING_DATASOURCE_LOGABANDONED = false
      - SPRING_DATASOURCE_URL = "jdbc:mysql://mysql:3306/actio?CHARACTERENCODING=UTF-8"
      - SPRING_DATASOURCE_USERNAME = "actio"
      - SPRING_DATASOURCE_PASSWORD = "actio"
      
  modeler:
    image: actio/modeler
    restart: always
    expose:
      - 8080
    environment:
      - ACTIO_MODELER_ENGINE_URL-FORMAT = "http://engine:8081/{path}"
 